name: Build book
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up book repository
        uses: actions/checkout@v6
        with:
          path: book
      - name: Compile book
        uses: xu-cheng/latex-action@v4
        with:
          working_directory: book
          root_file: book.tex
      # Check file and uploads
      - name: Run a multi-line script
        run: |
          # Output the directory contents for debugging
          ls -l book
          # Clone autogen repository (target for the file)
          git clone https://gcarcassi:${{ secrets.AUTOGEN_TOKEN }}@github.com/assumptionsofphysics/autogen autogen
          cd autogen
          mv book/book.pdf AssumptionsOfPhysicsDraft2.pdf
          ls -l
          git add AssumptionsOfPhysicsDraft2.pdf
          # Commit and push only if there were changes
          if ! git diff --cached --quiet; then
            git config user.name "gcarcassi[bot]"
            git config user.email "gabriele.carcassi@gmail.com"
            git pull
            git commit -m "Updating book draft"
            git push
          else
            echo "No changes to commit."
          fi
